config:
  aws:region: us-east-1
  eks-kuma-cfk:environment: prod
  eks-kuma-cfk:vpcId: vpc-0987654321fedcba0
  eks-kuma-cfk:publicSubnetIds:
    - subnet-1aaa000000000000a
    - subnet-1bbb000000000000b
    - subnet-1ccc000000000000c
  eks-kuma-cfk:privateSubnetIds:
    - subnet-1ddd000000000000d
    - subnet-1eee000000000000e
    - subnet-1fff000000000000f
  eks-kuma-cfk:eksClusterName: eks-prod
  eks-kuma-cfk:eksVersion: "1.29"
  eks-kuma-cfk:nodeInstanceTypes:
    - m5.xlarge
  eks-kuma-cfk:nodeDesiredSize: "3"
  eks-kuma-cfk:nodeMinSize: "3"
  eks-kuma-cfk:nodeMaxSize: "10"
  eks-kuma-cfk:eksPublicAccess: "false"
  eks-kuma-cfk:kumaVersion: "2.9.1"
  eks-kuma-cfk:cfkVersion: "0.1033.3"
  eks-kuma-cfk:confluentCloudBootstrap: pkc-yyyyy.us-east-1.aws.confluent.cloud:9092
  # Set secrets with: pulumi config set --secret confluentCloudApiKey <value>
  # eks-kuma-cfk:confluentCloudApiKey:
  # eks-kuma-cfk:confluentCloudApiSecret:
